name: Install, Test, and Run GeneFlow Docker Container

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install_test_run_docker:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Create virtual environment
      run: |
        python3 -m venv gfpy
        source gfpy/bin/activate

    - name: Clone GeneFlow repository
      run: git clone https://github.com/enochnet/geneflow2

    - name: Install GeneFlow
      run: pip install ./geneflow2

    - name: Test installation
      run: geneflow --help

    - name: Navigate to Docker directory
      run: cd geneflow2/docker

    - name: Build Docker image
      run: docker build -t geneflow .

    - name: Run Docker container
      run: docker run --rm -it geneflow