name: Build GeneFlow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx
          sudo apt install -y latexmk texlive texlive-science texlive-formats-extra

      - name: Generate Documentation
        run: |
          cd docs
          make html
          make latexpdf

      - name: Build GeneFlow
        run: |
          python3 -m venv gfpy
          source gfpy/bin/activate
          pip3 install ./geneflow2


